version: "3"

services:
  deathstar_backend_srv:
    env_file: ./.env
    container_name: deathstar_api
    build: ./
    links:
      - deathstar_database_srv
    depends_on:
      - deathstar_database_srv
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"

  deathstar_database_srv:
    container_name: deathstar_db
    image: postgres:latest
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    volumes:
      - deathstar_database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}

volumes:
  deathstar_database_volume:
